server.servlet.context-path=/SmartRegression
server.port=8081
test-tool-url=https://api.zephyrscale.smartbear.com/v2/issuelinks/{jiraId}/testcases
qtest-url=https://touchlessreg.qtestnet.com/api/v3/projects/{projectId}/requirements/trace-matrix-report
jenkins-url=http://localhost:8080/job
jenkins-userName=admin
jenkins-userPwd=c8cac181ffb3438c90bc8cc601245461
jenkins-userAPIToken=1176c7674a185ec37296d2add780395c78
use-qtest=false
projectId=8101
zephyre-key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczovL3RvdWNoLWJhc2UtcmVnLmF0bGFzc2lhbi5uZXQiLCJ1c2VyIjp7ImFjY291bnRJZCI6IjcxMjAyMDpmMjcxOGJlZC05OTg5LTQxYjgtODRhZC0yOTMyZGNjNmI1NjciLCJ0b2tlbklkIjoiNjY5YTNiZTEtOWU2OC00ZTE5LWE3MTEtYTNkMjEwMGEzNzgyIn19LCJpc3MiOiJjb20ua2Fub2FoLnRlc3QtbWFuYWdlciIsInN1YiI6ImRkMDcyZWM5LTJkZGEtMzIwYi1hODU5LWYzOGUzZjIxMDg4YyIsImV4cCI6MTc4MjM3NTczNywiaWF0IjoxNzUwODM5NzM3fQ.vviCjC8fiS4tStTs050D9XPDjFappGo6SjxFXLZXLdI
qtest-key=abc
application-job-name=ShoppingCart-Services
jiraId-pattern=DSC-[0-9]+
application-healthcheck-url=http://localhost:8083/actuator/health
MLModel-url=http://127.0.0.1:5000/match
